name: Pull Request to release branch

on:
  workflow_call:
    inputs:
      java-version:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          server-id: github
          server-username: MAVEN_USER
          server-password: MAVEN_TOKEN
          distribution: temurin
          java-version: ${{ inputs.java-version }}
          cache: maven

      - name: Build and test
        env: 
          MAVEN_USER: ${{ vars.MAVEN_USER }}
          MAVEN_TOKEN: ${{ secrets.MAVEN_TOKEN }}
        run: |
          ./mvnw --batch-mode --update-snapshots verify

      - uses: actions/upload-artifact@v4
        with:
          name: built-jars
          path: "**/target/*.jar"
          retention-days: 1
