name: Pull Request to release branch

on:
  workflow_call:
    inputs:
      java-version:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ inputs.java-version }}
          cache: maven

      - name: Configure package repository credentials
        uses: s4u/maven-settings-action@v3.1.0

      - name: Build and test
        run: >
          ./mvnw --batch-mode --update-snapshots verify

      - uses: actions/upload-artifact@v4
        with:
          name: built-jars
          path: "**/target/*.jar"
          retention-days: 1
