name: Release

on:
  workflow_call:
    inputs:
      java-version:
        required: true
        type: string

      release-branch:
        type: string
        default: 'main'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: "${{ inputs.release-branch }}"

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          server-id: github
          server-username: MAVEN_USER
          server-password: MAVEN_TOKEN
          distribution: temurin
          java-version: ${{ inputs.java-version }}
          cache: maven

      - name: Configure Git user
        env:
          GITHUB_CI_USER: MhikesCI
          GITHUB_CI_EMAIL: ops@mhikes.com

        run: |
          git config --global user.name "$GITHUB_CI_USER"
          git config --global user.email "$GITHUB_CI_EMAIL"

      - name: Publish package to GitHub Packages
        id: build
        env:
          MAVEN_USER: ${{ vars.MAVEN_USER }}
          MAVEN_TOKEN: ${{ secrets.MAVEN_TOKEN }}
        run: |
          ./mvnw --batch-mode release:prepare release:perform
