name: Snapshot

on:
  workflow_call:
    inputs:
      java-version:
        required: true
        type: string



jobs:
  snapshot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: ${{ inputs.java-version }}
          cache: maven

      - name: Configure Nexus credentials
        uses: s4u/maven-settings-action@v2.6.0
        with:
          servers: |
            [
              {"id": "mhikes-snapshots", "username": "github-actions", "password": "${{ secrets.MHIKES_NEXUS }}"},
              {"id": "mhikes-releases", "username": "github-actions", "password": "${{ secrets.MHIKES_NEXUS }}"},
              {"id": "old-mhikes-releases", "username": "github-actions", "password": "${{ secrets.MHIKES_NEXUS }}"}
            ]

      - name: Build, test, and push to Nexus
        run: |
          mvn -B deploy
