name: Snapshot

on:
  workflow_call:
    inputs:
      java-version:
        required: true
        type: string

jobs:
  snapshot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          server-id: github
          server-username: MAVEN_USER
          server-password: MAVEN_TOKEN
          distribution: temurin
          java-version: ${{ inputs.java-version }}
          cache: maven
          # Default:
          # cache-dependency-path: '**/pom.xml'

      - name: Publish package to GitHub Packages
        env:
          MAVEN_USER: ${{ vars.MAVEN_USER }}
          MAVEN_TOKEN: ${{ secrets.MAVEN_TOKEN }}
        run: |
          ./mvnw --batch-mode --update-snapshots deploy